<h1>Slicing Arrays</h1>

In [9]:
import numpy as np

In [1]:
my_vector = np.array([-17, -4, 0, 2, 21, 37, 105])

<IPython.core.display.Javascript object>

In [4]:
my_vector[0]

-17

In [8]:
# adding a new number
my_vector[0] = 102
my_vector

array([102,  -4,   0,   2,  21,  37, 105])

In [7]:
my_vector[-3]

21

In [9]:
# remainder
305 % 7

4

In [10]:
my_vector[305 % 7]

21

In [11]:
my_vector.size

7

In [12]:
my_vector[305 % my_vector.size]

21

In [15]:
my_array = np.arange(35)
my_array.shape = (7, 5)
my_array

<IPython.core.display.Javascript object>

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [16]:
# returning second 
my_array[2]

array([10, 11, 12, 13, 14])

In [25]:
# returning second to last row
my_array[-2]

array([25, 26, 27, 28, 29])

In [26]:
# returning single values
my_array[5, 2]

27

In [28]:
row = 5
column = 2
my_array[row, column]

27

## Three Dimensional Arrays

In [29]:
my_3d_array = np.arange(70)
my_3d_array.shape = (2, 7, 5) # dimension, row, column
my_3d_array

<IPython.core.display.Javascript object>

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [30]:
# getting a 2-dimension array from a 3-dimensional one
my_3d_array[1] 

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [31]:
# second dimensional array and the fourth row
my_3d_array[1, 3]

array([50, 51, 52, 53, 54])

In [32]:
# second array, third row, and the second column
my_3d_array[1, 3, 2]

52

In [34]:
my_3d_array[1, 3, 2] = 1111
my_3d_array

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51, 1111,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])