<h1>Broadcasting</h1>

In [1]:
import numpy as np

In [3]:
# Creating elements 0 to 69
my_3D_array = np.arange(70)
# Changing the shape of the array
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [5]:
# Checking the shape
my_3D_array.shape

(2, 7, 5)

In [7]:
# number of dimensions using .ndim atribute
my_3D_array.ndim

3

In [8]:
# size; number of elements
my_3D_array.size

70

In [9]:
# data type for each element
my_3D_array.dtype

dtype('int64')

In [10]:
5 * my_3D_array - 2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [13]:
left_mat = np.arange(6).reshape((2, 3)) # 2 rows and 3 columns
right_mat = np.arange(15).reshape((3, 5)) # 3 rows and 5 columns

In [14]:
np.inner(left_mat, right_mat)

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [16]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

## Operations along axes

In [17]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [18]:
my_3D_array.sum()

2415

In [19]:
(69 * 70) / 2

2415.0

In [29]:
# sum one matrix to the other
my_3D_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [30]:
# sum of the numbers by column
my_3D_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [32]:
# sum of the numbers by row
my_3D_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

## Broadcasting rules

In [37]:
# Creating an array using ones, adding 35 numbers, setting yp to integer type, 
# reshaping to 7, 5 and multiplying by 3
my_2d_array = np.ones(35, dtype='int_').reshape((7, 5)) * 3
my_2d_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [43]:
# Creating a random matrix
my_random_2d_array = np.random.random((7,5))
my_random_2d_array

array([[0.4996, 0.9252, 0.7996, 0.9142, 0.8382],
       [0.0858, 0.9103, 0.9317, 0.631 , 0.6282],
       [0.3734, 0.8208, 0.8338, 0.6186, 0.0395],
       [0.7189, 0.1777, 0.8925, 0.0957, 0.8239],
       [0.8093, 0.5871, 0.3872, 0.0451, 0.634 ],
       [0.3496, 0.3719, 0.1901, 0.4242, 0.6526],
       [0.4424, 0.8737, 0.5201, 0.8167, 0.1534]])

In [45]:
# setting up the array to have only 4 digits after points
np.set_printoptions(precision=4)
# multiplying the array
my_3D_array * my_random_2d_array

array([[[ 0.    ,  0.9252,  1.5993,  2.7426,  3.3528],
        [ 0.4291,  5.4618,  6.5219,  5.0476,  5.6537],
        [ 3.7335,  9.0283, 10.0057,  8.0414,  0.5532],
        [10.7828,  2.8425, 15.1725,  1.7229, 15.6532],
        [16.1854, 12.3289,  8.5181,  1.0379, 15.2157],
        [ 8.741 ,  9.6702,  5.1314, 11.8784, 18.9259],
        [13.2718, 27.0832, 16.6424, 26.9495,  5.2146]],

       [[17.4849, 33.3089, 29.5864, 34.7395, 32.6894],
        [ 3.4329, 37.3223, 39.1314, 27.1309, 27.6404],
        [16.8008, 37.7547, 39.189 , 29.6911,  1.9361],
        [35.9426,  9.0604, 46.4099,  5.0731, 44.488 ],
        [44.5099, 32.8771, 22.0697,  2.6174, 37.4053],
        [20.9785, 22.6878, 11.7832, 26.7265, 41.7675],
        [28.7556, 57.661 , 34.845 , 55.5322, 10.5826]]])