<h1>linspace(), zeros(), ones(), and NumPy data types</h1>

In [1]:
import numpy as np

In [2]:
# Creates an array that the elements are evenly spaced over specified interval
# The last number is included
np.linspace(5, 15, 9)

<IPython.core.display.Javascript object>

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [6]:
# retstep returns the step size
my_linspace = np.linspace(5, 15, 9, retstep=True)
my_linspace

<IPython.core.display.Javascript object>

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [8]:
# Getting only the stepsize
my_linspace[1]

1.25

## zeros()

In [10]:
# creates a list of zeros with floats
np.zeros(5)

<IPython.core.display.Javascript object>

array([0., 0., 0., 0., 0.])

## ones

In [11]:
np.ones(7)

<IPython.core.display.Javascript object>

array([1., 1., 1., 1., 1., 1., 1.])

In [14]:
# creating dimentional arrays
np.zeros((5,4))

<IPython.core.display.Javascript object>

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Two squared brackets means that it's a 2-dimentional array

In [16]:
# creating a 3-dimmentional array
np.zeros((5,4, 3))

<IPython.core.display.Javascript object>

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
# creating the type of data
np.zeros(11, dtype='int64')

<IPython.core.display.Javascript object>

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.zeros(11)

<IPython.core.display.Javascript object>

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])