<h1>Boolean Mask Arrays</h1>

In [1]:
import numpy as np

In [2]:
my_vector = np.array([-17, -4, 0, 2, 21, 37, 105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [3]:
# creating an array of boolean values showing if the number if dividible by 7
zero_mod_7_mask = 0 == (my_vector % 7)
zero_mod_7_mask

array([False, False,  True, False,  True, False,  True])

In [4]:
# indexing the variable that we created above
# boolean mask arrays
sub_array = my_vector[zero_mod_7_mask]
sub_array

array([  0,  21, 105])

In [5]:
sub_array[sub_array>0]

array([ 21, 105])

## NumPy Logical Operators

In [6]:
mod_test = 0 == (my_vector % 7 )
mod_test

array([False, False,  True, False,  True, False,  True])

In [7]:
positive_test = my_vector > 0
positive_test

array([False, False, False,  True,  True,  True,  True])

In [8]:
combined_mask = np.logical_and(mod_test, positive_test)
combined_mask

array([False, False, False, False,  True, False,  True])

In [9]:
my_vector[combined_mask]

array([ 21, 105])

In [34]:
numbers = list(range(0,21))
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

## Returning even numbers using NumPy and Python

In [35]:
def return_even(numbers):
    numbers = np.array(numbers)
    numpy_mask = 0 == (numbers % 2)
    even_numbers = numbers[numpy_mask]
    return even_numbers

In [36]:
return_even(numbers)

<IPython.core.display.Javascript object>

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [37]:
def return_even_python(numbers):
    even = []
    for n in numbers:
        if n % 2 == 0:
            even.append(n)
    return even

In [38]:
return_even_python(numbers)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]