<h2>Intrinsic NumPy array creation using NumPy's methods</h2>

In [1]:
import numpy as np

In [4]:
# creates an array
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
# with start and stop parameter
np.arange(10, 23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [9]:
# Counting the number of items
np.arange(10, 23) - 10 + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [11]:
# Using Python
len(np.arange(10, 23))

13

In [16]:
# Using .size
my_range_array = np.arange(10, 23)
my_range_array.size

13

In [17]:
np.arange(10, 23).size

13