<h1>Create NumPy arrays using Python's "array like" data types</h1>


In [1]:
import numpy as np

In [4]:
# checking numpy version
print(np.__version__)

1.18.5


In [10]:
# creating python list
my_list = [-17, 0, 4, 5, 9]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [12]:
# Multiplying every value by 10
my_array_from_list * 10

array([-170,    0,   40,   50,   90])

In [15]:
my_tuple = (14, -3.54, 5+7j)
np.array(my_tuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

### Difference between python and numpy data structure

In [16]:
# Python just repeats the data 6 times
my_tuple * 6

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [18]:
# Numpy arrays multiplicates each number
np.array(my_tuple) * 6

array([ 84.   +0.j, -21.24 +0.j,  30.  +42.j])